
* TODO Configurer emacs
* Eclipse 4 Tutoriel
** Chapitre 10
- To create object according to Dependency Injection we have to use : ContextInjectionFactory.make


* Soucis à analyser
- 
- Bug de la personne qui paie deux fois

* Points intéressants
- [ ] Lien http://doc.prestashop.com/pages/viewpage.action?pageId=3506242#Ajouterdesproduitsetdescat%C3%A9goriesdeproduits-Cr%C3%A9erunpackdeproduits
- [ ] Etudier la solution OpenERP

* <2013-09-06 ven.> PYC à réussi à convertir JAjoutProduit pour qu'il soit compatible avec JPrestaRest


* <2013-09-09 lun. 09:00> Rania rapporte que deux machines sont en pannes dans la boutique
  Cause : Les machines avaient un conflit d'adresse IP.
  Solution : Dans l'interface du routeur effacer les baux DHCP.

* <2013-09-09 lun.> Panne du serveur tissus-price.com
  10h39 : Panne
  11h00 : Rétablissement
  Cause : L'hébergement OVH n'avait pas été renouvellé.
  Solution : Mettre l'hébergement en automatique.
* Composition d'une application Eclipse E4

** OSGI Context

*** Workbench Context

**** Trimmed Window Context

***** Part Context
